/**
 * @file Version.h
 * @brief Version information for SCD41.
 *
 * This file is AUTO-GENERATED by scripts/generate_version.py from library.json.
 * DO NOT EDIT MANUALLY. Update version metadata via library.json or
 * scripts/generate_version.py bump/set commands.
 */

#pragma once

#include <stdint.h>

#ifndef SCD41_VERSION_STRING
#define SCD41_VERSION_STRING "0.1.0"
#endif

#ifndef SCD41_BUILD_DATE
#define SCD41_BUILD_DATE __DATE__
#endif

#ifndef SCD41_BUILD_TIME
#define SCD41_BUILD_TIME __TIME__
#endif

#ifndef SCD41_BUILD_TIMESTAMP
#define SCD41_BUILD_TIMESTAMP SCD41_BUILD_DATE " " SCD41_BUILD_TIME
#endif

#ifndef SCD41_GIT_COMMIT
#define SCD41_GIT_COMMIT "unknown"
#endif

#ifndef SCD41_GIT_STATUS
#define SCD41_GIT_STATUS "unknown"
#endif

#ifndef SCD41_VERSION_FULL
#define SCD41_VERSION_FULL SCD41_VERSION_STRING " (" SCD41_GIT_COMMIT ", " SCD41_BUILD_TIMESTAMP ", " SCD41_GIT_STATUS ")"
#endif

namespace SCD41 {

/// @brief Major version (breaking changes).
static constexpr uint16_t VERSION_MAJOR = 0;

/// @brief Minor version (backward-compatible features).
static constexpr uint16_t VERSION_MINOR = 1;

/// @brief Patch version (backward-compatible fixes).
static constexpr uint16_t VERSION_PATCH = 0;

/// @brief Full semantic version string.
static constexpr const char* VERSION = SCD41_VERSION_STRING;

/// @brief Encoded version for numeric comparison: MAJOR*10000 + MINOR*100 + PATCH.
static constexpr uint32_t VERSION_CODE = 100;

/// @brief Backward-compatible alias used by older repositories.
static constexpr int VERSION_INT = 100;

/// @brief Build date string.
static constexpr const char* BUILD_DATE = SCD41_BUILD_DATE;

/// @brief Build time string.
static constexpr const char* BUILD_TIME = SCD41_BUILD_TIME;

/// @brief Build timestamp string.
static constexpr const char* BUILD_TIMESTAMP = SCD41_BUILD_TIMESTAMP;

/// @brief Git commit string.
static constexpr const char* GIT_COMMIT = SCD41_GIT_COMMIT;

/// @brief Git working tree status string.
static constexpr const char* GIT_STATUS = SCD41_GIT_STATUS;

/// @brief Full version string with build metadata.
static constexpr const char* VERSION_FULL = SCD41_VERSION_FULL;

}  // namespace SCD41
